# Generated by Django 4.0.6 on 2022-11-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email2', models.EmailField(max_length=254)),
                ('pwd2', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user2',
            },
        ),
    ]
